### ISSUE TITLE
Document shared tsconfig across packages

### ISSUE THREAD

**Issue by NateRadebaugh** [Thinkmill/monorepo-starter#15]
Maybe thinkmill doesn't use typescript in their monorepos and don't see the need for it in their monorepo-starter, but it would be good to see what the guidance is for avoiding duplicate tsconfig across multiple packages.

My guess is the guidance would be to have a `tsconfig.json` file in the root of the monorepo, and then either a. not require anything down below because `preconstruct` will use the one from the root, or b. add simple `tsconfig.json` file with `extends: "../tsconfig.json"` or something like that.

What do you think?

**Comment by NateRadebaugh** [comment]
Unless you want to update the starter to use TypeScript, maybe could just reference to ts docs: https://www.typescriptlang.org/tsconfig#extends

**Comment by Noviny** [comment]
Hey Nate, this is a great idea! We're still a bit split on whether we use typescript ourselves, but if you wanted to PR an update to the section 'quick start guide for some other tools', that would be great.

**Comment by NateRadebaugh** [comment]
I made this issue so I tried to think it through a little. Added a PR to add some docs. Not sure what the best tsconfig is, but it's something.
